version: "2"

networks:
  lnmp:

services:
  lnmp-php-fpm:
    build: "php-fpm"
    networks:
      - lnmp
    volumes:
      - $PWD/html:/var/www/html:rw
    depends_on:
      - "lnmp-mysql"
    ports:
      - "9000:9000"

  lnmp-nginx:
    image: nginx
    networks:
      - lnmp
    volumes:
      - $PWD/html:/var/www/html:rw
      - $PWD/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - "lnmp-php-fpm"
    ports:
      - "8088:80"
  
  lnmp-mysql:
    image: "mysql:5.7.15"
    networks:
      - lnmp
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: lnmp
      MYSQL_PASSWORD: lnmppasswod
    volumes:
      - $PWD/data:/var/lib/mysql
    ports:
      - "33060:3306"